/* Pose library. Contraction key: con = concentric, ecc = eccentric, iso = isometric, len = lengthening under stretch */
const POSES=[
{id:"mountain",name:"Mountain",sk:"Tadasana",family:"Standing",
 fig:{view:"front",trunk:90,neck:90,uL:-95,fL:-93,uR:-85,fR:-87,tL:-90,sL:-90,ftL:180,tR:-90,sR:-90,ftR:0},
 hl:["core"],joints:["hipL","hipR","ankleL","ankleR"],
 summary:"The reference position for every other pose. Nothing looks active, yet dozens of muscles make small isometric corrections every second to keep the body stacked over a small base.",
 actions:[["Spine","Neutral curves (cervical and lumbar lordosis, thoracic kyphosis)"],["Hips","Neutral extension"],["Knees","Extended, soft rather than locked"],["Ankles","Neutral; body sways slightly forward and back over the feet"],["Shoulders","Scapulae resting neutral, arms at the sides"]],
 muscles:[["Soleus and gastrocnemius","Control forward sway over the ankles","iso"],["Erector spinae","Hold the spine upright against gravity","iso"],["Gluteus medius","Keep the pelvis level side to side","iso"],["Transversus abdominis","Pressurize the trunk","iso"],["Quadriceps","Light engagement to hold knee extension","iso"]],
 contra:["Low blood pressure or dizziness when rising from the floor: pause before standing","Hyperextended knees: cue a micro-bend rather than locking"],
 adapt:["Feet hip-width apart for a wider base","Back of the body against a wall to feel alignment","Seated Mountain on a chair for limited standing endurance"],
 cue:"Feel your weight spread between the heel and the ball of each foot, then let the crown of the head float up."},
{id:"chair",name:"Chair",sk:"Utkatasana",family:"Standing",
 fig:{view:"side",trunk:70,neck:72,uL:75,fL:75,uR:75,fR:75,tL:-25,sL:-100,ftL:0,tR:-25,sR:-100,ftR:0},
 hl:["thighR","core"],joints:["hipR","kneeR","ankleR"],
 summary:"A closed-chain squat. Lowering into the pose is eccentric work for the quadriceps and gluteals, and holding it is isometric, which is why thighs burn quickly.",
 actions:[["Hips","Flexion, about 70 to 90 degrees"],["Knees","Flexion"],["Ankles","Dorsiflexion"],["Spine","Neutral to slight extension; trunk hinges forward to balance"],["Shoulders","Flexion overhead with scapular upward rotation"]],
 muscles:[["Quadriceps","Lower the body, then hold the knee bend","ecc"],["Gluteus maximus","Control hip flexion and hold","iso"],["Erector spinae","Keep the spine long as the trunk leans","iso"],["Anterior and middle deltoid","Hold the arms overhead","iso"],["Serratus anterior","Upwardly rotate the scapulae","iso"]],
 contra:["Knee pain: limit depth","Shoulder impingement: keep hands at the heart or on the hips"],
 adapt:["Shallower bend","Back against a wall","Block squeezed between the thighs to wake up the adductors","Hands on hips or at the heart"],
 cue:"Sit back as if lowering onto a chair behind you, and keep the knees tracking toward the second toes."},
{id:"warrior1",name:"Warrior I",sk:"Virabhadrasana I",family:"Standing",
 fig:{view:"side",trunk:90,neck:95,uL:95,fL:93,uR:92,fR:90,tL:-132,sL:-132,ftL:190,tR:-30,sR:-90,ftR:0},
 hl:["thighR","thighL"],joints:["hipL","hipR","kneeR"],
 summary:"The back hip is asked to extend while the pelvis faces forward. The strong Y-shaped iliofemoral ligament limits hip extension, so the pelvis tends to turn open or tip forward unless the stance is adjusted.",
 actions:[["Front hip","Flexion"],["Front knee","Flexion, toward 90 degrees, knee over the ankle"],["Back hip","Extension, limited by the iliofemoral ligament"],["Back ankle","Dorsiflexion with the foot turned out"],["Spine","Mild extension"],["Shoulders","Flexion overhead"]],
 muscles:[["Front quadriceps","Hold the knee bend","iso"],["Back iliopsoas and rectus femoris","Lengthened by back-hip extension","len"],["Back gluteus maximus","Holds the back hip in extension","iso"],["Erector spinae","Support the lifted chest","iso"],["Deltoids and serratus anterior","Hold the arms overhead","iso"]],
 contra:["Shoulder injury: hands on hips","Knee pain in the front leg: shorten the stance and bend less","Low back discomfort: reduce the backbend, shorten stance"],
 adapt:["Wider stance, feet on 'railroad tracks', lets the pelvis face forward","Back heel lifted (high lunge)","Hands on hips"],
 cue:"Step the feet wider apart, like standing on railroad tracks, so the back hip can let the pelvis face forward."},
{id:"warrior2",name:"Warrior II",sk:"Virabhadrasana II",family:"Standing",
 fig:{view:"front",trunk:90,neck:90,uL:180,fL:180,uR:0,fR:0,tL:-145,sL:-145,ftL:185,tR:-15,sR:-90,ftR:0},
 hl:["thighR","armL","armR"],joints:["hipR","kneeR","shoulderL","shoulderR"],
 summary:"The pelvis faces the side of the mat, so the front hip combines flexion, abduction and external rotation. Keeping the front knee tracking over the second toe is a job for the hip's external rotators and gluteus medius.",
 actions:[["Front hip","Flexion, abduction and external rotation"],["Front knee","Flexion, tracking over the second toe"],["Back hip","Abduction, neutral to slight extension"],["Back knee","Extended"],["Shoulders","Abduction to 90 degrees"]],
 muscles:[["Front quadriceps","Hold the knee bend","iso"],["Front gluteus medius and deep rotators","Keep the knee from collapsing inward","iso"],["Back leg adductors","Lengthened by the wide stance","len"],["Middle deltoid and supraspinatus","Hold the arms out","iso"],["Trapezius","Support the shoulder girdle","iso"]],
 contra:["Knee pain: bend less, keep the knee behind the toes","Shoulder fatigue or injury: hands on hips"],
 adapt:["Shorter stance","Chair under the front thigh","Hands on hips"],
 cue:"Draw the front knee gently toward the pinky-toe side so it stays over the ankle."},
{id:"triangle",name:"Triangle",sk:"Utthita Trikonasana",family:"Standing",
 fig:{view:"front",trunk:15,neck:15,uL:90,fL:90,uR:-90,fR:-90,tL:-125,sL:-125,ftL:185,tR:-55,sR:-55,ftR:0},
 hl:["thighR"],joints:["hipR","hipL"],
 summary:"The pelvis tips over the front thigh (hip flexion) while both knees stay straight. The front hamstrings lengthen, and the length of the trunk depends on how far the pelvis can tilt, not how far the hand reaches.",
 actions:[["Front hip","Flexion with external rotation"],["Back hip","Abduction"],["Knees","Both extended; watch for hyperextension"],["Spine","Long, with a small lateral flexion and rotation"],["Shoulders","Abduction, arms in one vertical line"]],
 muscles:[["Front hamstrings","Lengthen as the pelvis tilts","len"],["Top-side obliques and quadratus lumborum","Hold the trunk against gravity","iso"],["Front quadriceps","Hold the knee straight without locking it","iso"],["Back leg gluteus medius","Stabilize the pelvis","iso"],["Deltoids","Hold the arm line","iso"]],
 contra:["Hypermobile front knee: keep a micro-bend","Neck problems: look down instead of up","Low blood pressure: come up slowly"],
 adapt:["Block under the bottom hand","Back of the body against a wall","Shorter stance"],
 cue:"Reach long through the front fingertips first, then tilt; the hand lands wherever it lands."},
{id:"tree",name:"Tree",sk:"Vrksasana",family:"Balance",
 fig:{view:"front",trunk:90,neck:90,uL:70,fL:80,uR:110,fR:100,tL:-140,sL:-30,ftL:0,tR:-90,sR:-90,ftR:0},
 hl:["thighR"],joints:["hipR","ankleR","hipL"],
 summary:"A single-leg balance. The standing-side gluteus medius keeps the pelvis level, while the foot and ankle make constant small corrections guided by proprioception and the vestibular system.",
 actions:[["Standing hip","Neutral; pelvis held level"],["Standing ankle","Constant small inversion and eversion corrections"],["Lifted hip","Flexion, abduction and external rotation"],["Lifted knee","Flexion"],["Shoulders","Flexion overhead or hands at the heart"]],
 muscles:[["Standing gluteus medius","Stop the opposite hip from dropping","iso"],["Peroneals and tibialis posterior","Balance side to side at the ankle","iso"],["Foot intrinsics","Grip and spread the foot","iso"],["Lifted-leg deep external rotators","Turn the knee out","iso"],["Adductors of the standing leg","Press back against the lifted foot","iso"]],
 contra:["Never press the foot into the side of the knee","Balance or vestibular problems: use a wall"],
 adapt:["Kickstand: toes on the floor, heel on the ankle","Hand on a wall","Hands at the heart"],
 cue:"Press the foot and the standing leg into each other with equal force."},
{id:"dog",name:"Downward-Facing Dog",sk:"Adho Mukha Svanasana",family:"Inversion",
 fig:{view:"side",trunk:-40,neck:-40,uL:-50,fL:-55,uR:-50,fR:-55,tL:-110,sL:-100,ftL:-20,tR:-110,sR:-100,ftR:-20},
 hl:["thighR","shinR","armR"],joints:["shoulderR","hipR","ankleR"],
 summary:"An inverted V with weight shared between hands and feet. The shoulders are in full flexion, the serratus anterior holds the scapulae against the ribs, and the whole back line of the legs lengthens.",
 actions:[["Shoulders","Flexion with scapular upward rotation"],["Elbows","Extension"],["Wrists","Extension under load"],["Hips","Flexion"],["Knees","Extension (or bent)"],["Ankles","Dorsiflexion"],["Spine","Long and neutral"]],
 muscles:[["Serratus anterior","Upwardly rotate and hold the scapulae","iso"],["Triceps","Keep the elbows straight","iso"],["Hamstrings and gastrocnemius","Lengthen along the back of the legs","len"],["Quadriceps","Hold the knees straight; reciprocal inhibition helps the hamstrings release","iso"],["Deltoids","Hold the shoulders in flexion","iso"]],
 contra:["Wrist pain or carpal tunnel: forearm version","Uncontrolled high blood pressure or glaucoma: head below the heart; keep it brief or use tabletop","Late pregnancy: shorten holds"],
 adapt:["Bend the knees generously","Hands on blocks","Forearm Dog","Puppy pose"],
 cue:"Bend the knees first and lift the sitting bones; straighten the legs only as far as the back stays long."},
{id:"chaturanga",name:"Four-Limbed Staff",sk:"Chaturanga Dandasana",family:"Arm support",
 fig:{view:"side",trunk:8,neck:10,uL:188,fL:-90,uR:188,fR:-90,tL:188,sL:188,ftL:-95,tR:188,sR:188,ftR:-95},
 hl:["armR","core"],joints:["shoulderR","elbowR"],
 summary:"The most repeated load in a Vinyasa class. Lowering from plank is eccentric work for the triceps and pectorals; the danger point is the shoulder dropping below the elbow, which rolls the humeral head forward.",
 actions:[["Shoulders","Extension, held at elbow height"],["Elbows","Flexion to about 90 degrees, hugging the ribs"],["Wrists","Extension under load"],["Hips and knees","Extended, body in one line"],["Ankles","Dorsiflexion, toes extended"]],
 muscles:[["Triceps brachii","Lower the body, then hold","ecc"],["Pectoralis major and anterior deltoid","Control the descent","ecc"],["Serratus anterior","Keep the scapulae on the ribcage","iso"],["Rectus abdominis and transversus abdominis","Stop the hips from sagging","iso"],["Quadriceps","Hold the legs straight","iso"]],
 contra:["Rotator cuff or anterior shoulder injury","Wrist pain","Later pregnancy"],
 adapt:["Knees down","Lower only halfway","Stay in plank","Blocks under the shoulders as a stopping point"],
 cue:"Shift forward in plank first, then lower only until the shoulders are level with the elbows."},
{id:"cobra",name:"Cobra",sk:"Bhujangasana",family:"Backbend",
 fig:{view:"side",trunk:45,neck:60,uL:-105,fL:-60,uR:-105,fR:-60,tL:195,sL:180,ftL:185,tR:195,sR:180,ftR:185},
 hl:["trunk"],joints:["pelvis","shoulderR"],
 summary:"A gentle spinal extension driven mostly by the back muscles, with the hands offering only light support. It spreads extension through the thoracic spine instead of hinging at the low back.",
 actions:[["Spine","Extension, thoracic and lumbar"],["Hips","Extension, pelvis on the floor"],["Shoulders","Extension with scapular retraction and depression"],["Elbows","Flexion, hugging in"]],
 muscles:[["Erector spinae","Lift the chest","con"],["Lower trapezius and rhomboids","Draw the shoulder blades back and down","iso"],["Rectus abdominis","Lengthened across the front","len"],["Gluteals and hamstrings","Lightly steady the pelvis and legs","iso"],["Triceps","Light support","iso"]],
 contra:["Acute low back pain, especially pain that worsens with extension","Pregnancy (lying prone)"],
 adapt:["Sphinx on the forearms","Lift the hands off the floor for a back-muscle-only version","Lower height"],
 cue:"Lift the chest with the back muscles; the hands only steady you."},
{id:"bridge",name:"Bridge",sk:"Setu Bandha Sarvangasana",family:"Backbend",
 fig:{view:"side",trunk:210,neck:185,uL:-2,fL:0,uR:-2,fR:0,tL:15,sL:-85,ftL:0,tR:15,sR:-85,ftR:0},
 hl:["thighR"],joints:["hipR","kneeR"],
 summary:"A hip-extension pose. The gluteus maximus and hamstrings lift the pelvis; the neck is flexed under body weight, which is why turning the head is off-limits.",
 actions:[["Hips","Extension"],["Knees","Flexion, about 90 degrees"],["Spine","Moderate extension"],["Neck","Flexion; head still"],["Shoulders","Extension, arms on the floor"]],
 muscles:[["Gluteus maximus","Lift the pelvis","con"],["Hamstrings","Assist hip extension and hold","iso"],["Adductors","Keep the knees from splaying","iso"],["Erector spinae","Support the arch","iso"],["Hip flexors","Lengthened across the front","len"]],
 contra:["Neck injury: do not turn the head in the pose","Later pregnancy: limit time lying on the back"],
 adapt:["Block under the sacrum (supported bridge)","Lower lift","Block between the thighs"],
 cue:"Press into the heels and lift from the back of the pelvis; keep the eyes and chin still."},
{id:"forwardfold",name:"Seated Forward Fold",sk:"Paschimottanasana",family:"Forward fold",
 fig:{view:"side",trunk:35,neck:25,uL:-55,fL:30,uR:-55,fR:30,tL:0,sL:0,ftL:80,tR:0,sR:0,ftR:80},
 hl:["thighR","trunk"],joints:["hipR","pelvis"],
 summary:"Hip flexion plus spinal flexion with straight knees. Tight hamstrings anchor the sitting bones and hold the pelvis back, so the spine rounds to make up the difference.",
 actions:[["Hips","Flexion"],["Spine","Flexion"],["Knees","Extended"],["Ankles","Dorsiflexion"]],
 muscles:[["Hamstrings","Lengthen as the pelvis tilts forward","len"],["Erector spinae","Lengthen as the spine rounds","ecc"],["Iliopsoas","Draw the trunk toward the thighs at end range","con"],["Calf muscles","Lengthened by dorsiflexion","len"]],
 contra:["Acute disc herniation or sciatica: avoid loaded spinal flexion","Recent hamstring strain"],
 adapt:["Sit on a folded blanket so the pelvis can tilt forward","Bend the knees","Strap around the feet"],
 cue:"Sit up on a blanket and hinge from the hips; the goal is length, not the forehead on the shins."},
{id:"child",name:"Child's Pose",sk:"Balasana",family:"Rest",
 fig:{view:"side",trunk:-20,neck:-30,uL:-5,fL:0,uR:-5,fR:0,tL:-30,sL:180,ftL:180,tR:-30,sR:180,ftR:180},
 hl:["trunk"],joints:["hipR","kneeR"],
 summary:"A resting pose, but not a neutral one: knees and hips are in deep flexion and ankles in full plantarflexion, which some bodies find far from restful.",
 actions:[["Hips","Deep flexion"],["Knees","Full flexion"],["Ankles","Plantarflexion"],["Spine","Flexion"],["Shoulders","Flexion, arms forward"]],
 muscles:[["Erector spinae","Lengthened","len"],["Gluteus maximus","Lengthened","len"],["Quadriceps","Lengthened by deep knee flexion","len"],["Tibialis anterior","Lengthened by plantarflexion","len"]],
 contra:["Knee injury or replacement (deep flexion)","Later pregnancy: take the knees wide"],
 adapt:["Bolster under the torso","Blanket between calves and thighs","Knees wide","Forehead on a block"],
 cue:"Take the knees as wide as feels good and let the floor or a bolster hold the weight."}
];
