/* Flashcards: [deck, front, back] */
const CARDS=[
["Movement","Sagittal plane","Divides the body into left and right. Flexion and extension happen here: forward folds, backbends, Warrior I's front knee."],
["Movement","Frontal (coronal) plane","Divides front from back. Abduction, adduction and lateral flexion: Warrior II arms, side bends, Star pose."],
["Movement","Transverse plane","Divides top from bottom. Rotation happens here: twists, turning the thigh out in Warrior II."],
["Movement","Flexion","Decreasing the angle between two segments in the sagittal plane. Hip flexion brings the thigh toward the belly."],
["Movement","Abduction","Moving a limb away from the midline. Warrior II arms and the front hip in Goddess."],
["Movement","External (lateral) rotation","Turning a limb so its front faces away from the midline. The lifted hip in Tree pose."],
["Movement","Dorsiflexion","Bringing the top of the foot toward the shin. Both ankles in Chair and Downward Dog."],
["Movement","Plantarflexion","Pointing the foot away from the shin. Ankles in Child's pose and the tops of the feet in Cobra."],
["Bones","Acetabulum","The hip socket, formed where the ilium, ischium and pubis fuse. The femoral head sits in it."],
["Bones","Anterior superior iliac spine (ASIS)","The bony front point of the pelvis you feel as 'hip points'. Used to see whether the pelvis faces forward in Warrior I."],
["Bones","Ischial tuberosities","The 'sitting bones'. Hamstrings attach here, which is why tight hamstrings round the back in seated folds."],
["Bones","Greater trochanter","The bony knob on the outer upper thigh. Gluteus medius attaches here and stabilizes the pelvis in balances."],
["Bones","Scapula","The shoulder blade. It glides on the ribcage and must rotate upward for arms to go fully overhead."],
["Bones","Humerus","The upper arm bone. Its head sits in the shallow glenoid fossa of the scapula."],
["Bones","Seven cervical vertebrae","The neck. The smallest vertebrae carry the head, which is why headstand and shoulderstand need care."],
["Bones","Twelve thoracic vertebrae","The mid-back, each joined to a pair of ribs. Rotation happens easily here; extension less so."],
["Bones","Five lumbar vertebrae","The low back. Large bodies built for load; allows flexion and extension but very little rotation."],
["Joints","Synovial joint","A freely movable joint with a capsule, synovial fluid and cartilage-covered bone ends. Nearly every joint that moves in asana."],
["Joints","Ball-and-socket joint","A synovial joint allowing movement in all three planes. The hip and the shoulder."],
["Joints","Hinge joint","Moves mainly in one plane. The elbow; the knee is a modified hinge that tolerates little twisting."],
["Joints","Iliofemoral ligament","The Y-shaped ligament at the front of the hip, one of the strongest in the body. It limits hip extension in Warrior I's back leg."],
["Joints","Tension versus compression","Range stops at tension (tissue is tight and can change) or compression (bone meets bone or tissue and will not change)."],
["Joints","Passive stability","Stability from bone shape, ligaments and joint capsule. The hip has a lot; the shoulder has little."],
["Joints","Active stability","Stability supplied by muscle contraction. The rotator cuff does this for the shoulder in Chaturanga."],
["Muscles","Iliopsoas","The main hip flexor, running from the lumbar spine and inner pelvis to the femur. Lengthened in the back leg of lunges."],
["Muscles","Gluteus maximus","The prime hip extensor. Lifts the pelvis in Bridge and the legs in Locust."],
["Muscles","Gluteus medius","Hip abductor and pelvic stabilizer. Keeps the pelvis level on one leg in Tree and Warrior III."],
["Muscles","Hamstrings","Three muscles from the sitting bones to below the knee. They extend the hip and flex the knee; lengthened in forward folds."],
["Muscles","Quadriceps","Four muscles on the front of the thigh that extend the knee. Rectus femoris also crosses the hip."],
["Muscles","Serratus anterior","Holds the scapula to the ribs and rotates it upward. Critical in Plank, Downward Dog and arm balances."],
["Muscles","Rotator cuff","Supraspinatus, infraspinatus, teres minor and subscapularis. They center the humeral head in its socket."],
["Muscles","Transversus abdominis","The deepest abdominal layer, wrapping the trunk like a corset. Part of the pressure 'canister'."],
["Contraction","Concentric contraction","The muscle shortens while it works. Quadriceps as you rise out of Chair."],
["Contraction","Eccentric contraction","The muscle lengthens while it works, controlling a movement. Triceps lowering from Plank to Chaturanga."],
["Contraction","Isometric contraction","The muscle works without changing length. Holding Warrior II."],
["Contraction","Reciprocal inhibition","When an agonist contracts, its antagonist is signaled to relax. Engaging the quadriceps helps the hamstrings release in a fold."],
["Contraction","Stretch reflex","A quick stretch triggers a protective contraction via muscle spindles. Bouncing in a stretch provokes it."],
["Breath","Diaphragm","The primary muscle of inhalation. It contracts and descends, enlarging the chest cavity so air flows in."],
["Breath","How air enters","A bigger chest lowers pressure inside the lungs below the air outside, so air flows in. Exhale at rest is mostly passive recoil."],
["Breath","Accessory muscles of breathing","Scalenes, sternocleidomastoid and upper trapezius lift the upper ribs during effortful breathing."],
["Breath","Voluntary versus involuntary breath","The brainstem breathes for you automatically, driven mostly by carbon dioxide; the cortex can override it, which is what pranayama uses."],
["Breath","Ujjayi","Breathing with a slight narrowing of the glottis, making an audible sound. Slows airflow and gives the breath a pace."],
["Nervous","Autonomic nervous system","The involuntary system controlling heart rate, digestion and more. Two branches: sympathetic and parasympathetic."],
["Nervous","Sympathetic response","Fight or flight: raised heart rate, blood pressure and alertness, with adrenaline and cortisol release."],
["Nervous","Vagus nerve","Cranial nerve X, the main parasympathetic nerve, slowing the heart and supporting digestion. A longer exhale increases its effect on heart rate."],
["Nervous","Polyvagal theory","A model proposing three hierarchical autonomic states, including 'freeze'. Popular in yoga and trauma work; parts of its physiology are debated by researchers."],
["Nervous","Proprioception","The sense of body position from receptors in muscles, tendons and joints. Trained in every balance pose."],
["Nervous","Interoception","Sensing the internal state of the body: heartbeat, breath, hunger. Much of body-scan practice draws on it."],
["Safety","Contraindication","A condition that makes a pose or practice inadvisable for a particular person. Example: long inversions with uncontrolled glaucoma."],
["Safety","Hypermobility","Joint range beyond typical. These students need strength and end-range control more than more stretching."],
["Safety","Pain versus sensation","Stretch sensation is diffuse and fades as you ease out. Sharp, pinching, electric or joint-line pain is a signal to stop."],
["Safety","Scope of practice","Yoga teachers adapt and refer; they do not diagnose or treat. New or unexplained pain goes to a healthcare provider."]
];

/* The Chase questions: [question, [a,b,c], correctIndex] */
const QS=[
["Which plane do twists happen in?",["Sagittal","Frontal","Transverse"],2],
["Warrior II arms reaching out to the sides are in:",["Abduction","Flexion","Rotation"],0],
["Lowering from Plank to Chaturanga, the triceps contract:",["Concentrically","Eccentrically","Not at all"],1],
["Holding Warrior II still is mainly which contraction type?",["Isometric","Concentric","Eccentric"],0],
["The primary muscle of inhalation is the:",["Diaphragm","Rectus abdominis","Scalenes"],0],
["Which ligament limits hip extension in the back leg of Warrior I?",["Iliofemoral","Anterior cruciate","Sacrotuberous"],0],
["The hip socket is called the:",["Glenoid fossa","Acetabulum","Patella"],1],
["Which muscle keeps the pelvis level in Tree pose?",["Gluteus medius","Biceps femoris","Tibialis anterior"],0],
["Hamstrings attach at the:",["ASIS","Ischial tuberosities","Greater trochanter"],1],
["Which spinal region rotates the least?",["Cervical","Thoracic","Lumbar"],2],
["Serratus anterior mainly acts on the:",["Scapula","Pelvis","Femur"],0],
["The knee is best described as a:",["Ball-and-socket joint","Modified hinge joint","Pivot joint"],1],
["Exhalation at rest is mostly:",["Passive recoil","Forceful abdominal contraction","Driven by the scalenes"],0],
["The automatic drive to breathe comes mostly from:",["Oxygen levels","Carbon dioxide levels","Blood sugar"],1],
["The vagus nerve belongs to which branch?",["Sympathetic","Parasympathetic","Somatic motor"],1],
["A lengthened exhale tends to:",["Raise heart rate","Slow heart rate","Have no effect"],1],
["Fight or flight is driven by the:",["Sympathetic nervous system","Parasympathetic nervous system","Enteric nervous system"],0],
["Sensing the position of your limbs with eyes closed is:",["Interoception","Proprioception","Nociception"],1],
["Engaging the quadriceps to help the hamstrings release uses:",["Reciprocal inhibition","The stretch reflex","Eccentric loading"],0],
["Bouncing in a stretch tends to trigger the:",["Relaxation response","Stretch reflex","Golgi tendon reflex only"],1],
["Which rotator cuff muscle sits on top of the shoulder, above the spine of the scapula?",["Supraspinatus","Subscapularis","Teres major"],0],
["In Downward Dog the shoulders are in:",["Flexion","Extension","Adduction"],0],
["In Bridge the gluteus maximus is lifting the pelvis by:",["Hip flexion","Hip extension","Hip adduction"],1],
["A student with glaucoma should be cautious with:",["Long inversions","Seated twists","Mountain pose"],0],
["Knee pressing sideways from the foot in Tree is a problem because the knee:",["Tolerates little sideways force","Is a ball-and-socket joint","Has no ligaments"],0],
["Range that ends with bone meeting bone is limited by:",["Tension","Compression","Reciprocal inhibition"],1],
["For a hypermobile student the priority is:",["More passive stretching","Strength and control near end range","Locking the joints"],1],
["Sitting on a blanket in a forward fold helps because it:",["Tilts the pelvis forward","Stretches the calves","Rounds the spine more"],0],
["Which is NOT a synovial joint?",["Hip","Sutures of the skull","Shoulder"],1],
["Scalenes and sternocleidomastoid are:",["Accessory breathing muscles","Hip flexors","Rotator cuff muscles"],0],
["The shoulder gets most of its stability from:",["Bone shape","Muscle (active stability)","Its thick capsule"],1],
["How many lumbar vertebrae are typical?",["Five","Seven","Twelve"],0],
["Chair pose ankles are in:",["Plantarflexion","Dorsiflexion","Inversion"],1],
["A pinching pain at the front of the hip in a lunge means:",["Push further","Back off and adjust","Hold your breath"],1],
["Pointing the toes is:",["Dorsiflexion","Plantarflexion","Eversion"],1],
["A yoga teacher who suspects an injury should:",["Diagnose it","Adapt the practice and refer","Ignore it"],1],
["The transversus abdominis is the:",["Deepest abdominal layer","Most superficial abdominal","A hip rotator"],0],
["In Warrior II the front hip is in flexion, abduction and:",["Internal rotation","External rotation","Extension"],1],
["Getting up quickly after Savasana can cause dizziness because of:",["A drop in blood pressure on standing","Low carbon dioxide","Muscle fatigue"],0],
["Which hormone rises in a stress response?",["Cortisol","Insulin","Melatonin"],0],
["The idea that twists 'wring out toxins' from organs is:",["Well established","Not supported by physiology","Proven by lab tests"],1],
["Ujjayi breath narrows the:",["Glottis","Nostrils only","Diaphragm"],0],
["The ASIS is a landmark on the:",["Scapula","Pelvis","Femur"],1],
["In Chaturanga, the shoulders should stay:",["Level with or above the elbows","Below the elbows","Shrugged to the ears"],0],
["Tadasana balance is controlled mostly at the:",["Ankles","Wrists","Neck"],0]
];
